In [1]:
import numpy as np
import pandas as pd
import random
import timeit

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(np.__version__)

[1 2 3 4 5]
2.2.2


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim) # to check dimensions 
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [6]:
# Slicing 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # print from 1st index to 4th index
# The result includes the start index, but excludes the end index.

[2 3 4 5]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [8]:
'''  Data types :- 
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )'''

'  Data types :- \ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )'

In [9]:
print(arr.shape)

(2, 5)
